# docker-compose.yml
version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin14092025
      POSTGRES_DB: legal_assistant_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql://admin:admin14092025@db:5432/legal_assistant_db
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
